killall -9 PlayStarter.bin
killall -9 PlayBackManager.bin
killall -9 runner.bin
killall -9 alpha5.bin
killall -9 PlayerCCTV.bin
killall -9 PlaySender.bin
killall -9 SoundView.bin
killall -9 GrnMainFrame.bin
killall -9 LogViewer4
killall -9 ffplay